FROM php:7.4-apache

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git && \
    apt-get install -y libzip-dev && \
    apt-get install -y zip && \
    apt-get install -y unzip


RUN docker-php-ext-install pdo pdo_mysql zip


RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN a2enmod rewrite
